Resources:
  ImFrontendWebHostingBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      VersioningConfiguration:
        Status: Disabled
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendWebHostingBucket
  ImFrontendWebHostingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ImFrontendWebHostingBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: s3:GetObject
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ImFrontendWebHostingBucket
                      - Arn
                  - /*
            Effect: Allow
            Principal: "*"
            Sid: PublicReadAccess
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendWebHostingBucketPolicy
  ArtifactBucketId:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 1
            Id: DeleteOldArtifactsId
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ArtifactBucketId
  CodeBuildRoleId100E8946:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
      Description: Role für CodeBuild Projekt zum Bereitstellen von Angular Frontend
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/CodeBuildRoleId/Resource
  CodeBuildRoleIdDefaultPolicyD2F518EE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ImFrontendWebHostingBucket
                      - Arn
                  - /*
          - Action: s3:ListBucket
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - ImFrontendWebHostingBucket
                - Arn
          - Action:
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ArtifactBucketId
                      - Arn
                  - /*
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource: arn:aws:logs:eu-central-1:315735600242:log-group:/aws/codebuild/*
        Version: "2012-10-17"
      PolicyName: CodeBuildRoleIdDefaultPolicyD2F518EE
      Roles:
        - Ref: CodeBuildRoleId100E8946
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/CodeBuildRoleId/DefaultPolicy/Resource
  ImFrontendCodeBuildProjectId:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      AutoRetryLimit: 0
      BadgeEnabled: false
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: S3_BUCKET
            Type: PLAINTEXT
            Value:
              Ref: ImFrontendWebHostingBucket
          - Name: AWS_DEFAULT_REGION
            Type: PLAINTEXT
            Value: eu-central-1
          - Name: AWS_ACCOUNT_ID
            Type: PLAINTEXT
            Value: "315735600242"
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: /aws/codebuild/ImFrontendCICDBuildProjectL1
          Status: ENABLED
        S3Logs:
          Status: DISABLED
      QueuedTimeoutInMinutes: 480
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRoleId100E8946
          - Arn
      Source:
        BuildSpec: buildspec.yaml
        Type: CODEPIPELINE
      TimeoutInMinutes: 20
      Visibility: PRIVATE
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendCodeBuildProjectId
  ImFrontendPipelineRole25AA5723:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
        Version: "2012-10-17"
      Description: Diese Role Wird verwendet für Im-Fronend zum Bereitstellen von Frontend (Angular) im AWS Pipeline.
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendPipelineRole/Resource
  ImFrontendPipelineRoleDefaultPolicy0F7ADDC6:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - codeconnections:UseConnection
              - codestar-connections:UseConnection
            Effect: Allow
            Resource: arn:aws:codeconnections:eu-central-1:315735600242:connection/0eb84fa4-1c3f-4b0b-8434-a3f94184c621
          - Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - ImFrontendCodeBuildProjectId
                - Arn
          - Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:PutObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ArtifactBucketId
                      - Arn
                  - /*
          - Action:
              - s3:DeleteObject
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ImFrontendWebHostingBucket
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - ImFrontendWebHostingBucket
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: ImFrontendPipelineRoleDefaultPolicy0F7ADDC6
      Roles:
        - Ref: ImFrontendPipelineRole25AA5723
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendPipelineRole/DefaultPolicy/Resource
  ImFrontendPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location:
          Ref: ArtifactBucketId
        Type: S3
      RoleArn:
        Fn::GetAtt:
          - ImFrontendPipelineRole25AA5723
          - Arn
      Stages:
        - Actions:
            - ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: "1"
              Configuration:
                BranchName: develop
                FullRepositoryId: Digitalisierung/im-frontend
                OutputArtifactFormat: CODE_ZIP
                ConnectionArn: arn:aws:codeconnections:eu-central-1:315735600242:connection/0eb84fa4-1c3f-4b0b-8434-a3f94184c621
              Name: GitHub_Source
              OutputArtifacts:
                - Name: SourceOutput
          Name: Source
        - Actions:
            - ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName:
                  Ref: ImFrontendCodeBuildProjectId
              InputArtifacts:
                - Name: SourceOutput
              Name: CodeBuild
          Name: Build
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendPipeline
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/+2TwU7DMAyGn2U5TmnY1sOk3jZOcELdbtOEMscIr2lSNSnTFPXdUdqtgHpBgBAHTrG+P47tX85CLNJUzCby5BJQRaLpIMLGSyi4PLnH4FIRbp/MuoECPR+iB6sJzi0nWYqQW427wKRzTYlqfWZZYFVNBqiSegVgG+NZxqaMX+7EhBV4sqbDLWcKHdRUvUOBSaW2ti/Esl1o92/w+vhI9V7C853RZHDQ2JR9QvxCsd9J+Xf1p1P2cY+jW7zHsd1hkq2NymjAMVZq46XHEo13H8p+F/+pbjqvrr8drMJDQ1qJCGt7RPAdrKjCuAAdv8Qtz9HZpgbs/O07vZcv8ma+FDMxX06OjiipG+OpRJH35yuxwMsbkAQAAA==
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]