Resources:
  BucketForImFrontendCICDStackL19AC2CB0F:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      Tags:
        - Key: aws-cdk:auto-delete-objects
          Value: "true"
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/BucketForImFrontendCICDStackL1/Resource
  BucketForImFrontendCICDStackL1Policy0C72CA99:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: BucketForImFrontendCICDStackL19AC2CB0F
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              AWS: "*"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - BucketForImFrontendCICDStackL19AC2CB0F
                      - Arn
                  - /*
          - Action:
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:List*
              - s3:PutBucketPolicy
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
                  - Arn
            Resource:
              - Fn::GetAtt:
                  - BucketForImFrontendCICDStackL19AC2CB0F
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BucketForImFrontendCICDStackL19AC2CB0F
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/BucketForImFrontendCICDStackL1/Policy/Resource
  BucketForImFrontendCICDStackL1AutoDeleteObjectsCustomResource742D8BD6:
    Type: Custom::S3AutoDeleteObjects
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
          - Arn
      BucketName:
        Ref: BucketForImFrontendCICDStackL19AC2CB0F
    DependsOn:
      - BucketForImFrontendCICDStackL1Policy0C72CA99
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/BucketForImFrontendCICDStackL1/AutoDeleteObjectsCustomResource/Default
  CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/Custom::S3AutoDeleteObjectsCustomResourceProvider/Role
  CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-315735600242-eu-central-1
        S3Key: faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6.zip
      Timeout: 900
      MemorySize: 128
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
          - Arn
      Runtime: nodejs22.x
      Description:
        Fn::Join:
          - ""
          - - "Lambda function for auto-deleting objects in "
            - Ref: BucketForImFrontendCICDStackL19AC2CB0F
            - " S3 bucket."
    DependsOn:
      - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler
      aws:asset:path: asset.faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
      aws:asset:property: Code
  CodeBuildRole728CBADE:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/CodeBuildRole/Resource
  CodeBuildRoleDefaultPolicy829527DE:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - arn:aws:logs:eu-central-1:315735600242:log-group:/aws/codebuild/ImFrontendCICDStack
              - arn:aws:logs:eu-central-1:315735600242:log-group:/aws/codebuild/ImFrontendCICDStack:*
          - Action:
              - codeconnections:GetConnection
              - codeconnections:GetConnectionToken
              - codeconnections:UseConnection
              - codestar-connections:GetConnection
              - codestar-connections:GetConnectionToken
              - codestar-connections:UseConnection
            Effect: Allow
            Resource: arn:aws:codeconnections:eu-central-1:315735600242:connection/3baf9c01-87e6-408b-82af-6f37b63edecc
          - Action:
              - s3:Abort*
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:GetObject*
              - s3:List*
              - s3:PutObject
              - s3:PutObjectLegalHold
              - s3:PutObjectRetention
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - BucketForImFrontendCICDStackL19AC2CB0F
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - BucketForImFrontendCICDStackL19AC2CB0F
                        - Arn
                    - /*
        Version: "2012-10-17"
      PolicyName: CodeBuildRoleDefaultPolicy829527DE
      Roles:
        - Ref: CodeBuildRole728CBADE
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/CodeBuildRole/DefaultPolicy/Resource
  ImFrontendCICDBuuldProjectL1:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      AutoRetryLimit: 0
      BadgeEnabled: false
      Cache:
        Type: NO_CACHE
      EncryptionKey: alias/aws/s3
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: S3_BUCKET
            Type: PLAINTEXT
            Value:
              Ref: BucketForImFrontendCICDStackL19AC2CB0F
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: false
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          GroupName: /aws/codebuild/ImFrontendCICDStack
          Status: ENABLED
        S3Logs:
          Status: DISABLED
      QueuedTimeoutInMinutes: 480
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildRole728CBADE
          - Arn
      Source:
        Auth:
          Resource: arn:aws:codeconnections:eu-central-1:315735600242:connection/3baf9c01-87e6-408b-82af-6f37b63edecc
          Type: CODECONNECTIONS
        BuildSpec: buildspec.yaml
        GitCloneDepth: 1
        GitSubmodulesConfig:
          FetchSubmodules: false
        Location: https://github.com/Digitalisierung/im-frontend
        ReportBuildStatus: true
        Type: GITHUB
      SourceVersion: develop
      TimeoutInMinutes: 20
      Triggers:
        FilterGroups:
          - - Pattern: PUSH
              Type: EVENT
            - Pattern: refs/heads/develop
              Type: HEAD_REF
        Webhook: true
      Visibility: PRIVATE
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/ImFrontendCICDBuuldProjectL1
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/52ST2sbMRDFP0vmaGQ1iQ+Bva3jUFJoa+zcTAhaaZIo1kpGM7JrxH73sv8SXFMIOYl9v9G8N6O9ltezmby8UAeaarOdOlvJvGalt0Id6CnTTOZ50lvkTQaVOCzQIePv6g01ExQcEwqoXNDbZaqc1aXWSAQFTEAAeh2PO7bBQwHr2dPP8lf5/W4BAnZd8QqVGS/0nSLWYa/cMjirj1CAQeIYjiBgj5Fs8GigeFaOUMABK7KMdzGGuAg61eh5MB7QvTf45wQ1j+L22fcTif7ovTYZqu7zrKznjbCqlnkVHLabIEo1mvkRigy7aL22O+VKrUN6z9DXtBdKPaxgAk0jMihjHsI44iY3jx/i2OqMMiv9eu+d9fjOYAKfgF8w+z/t9tLOJIa1taOOCR5CS86CncvGrFkxtq9CJ7aflbsY48PoYLBK1hnZijG0v2YjbhNxqFdIIUWNnXeXfRD+4csY9tZgnCtCURIhr1m9WP8iTjo04ofaq29XN/JSXt1cvJG105g82xrlqj//AoLm6jtSAwAA
    Metadata:
      aws:cdk:path: ImFrontendCICDStackL1/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]