Resources:
  ImFrontendCICDStack81ACF762:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      Tags:
        - Key: aws-cdk:auto-delete-objects
          Value: "true"
      WebsiteConfiguration:
        ErrorDocument: error.html
        IndexDocument: index.html
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendCICDStack/Resource
  ImFrontendCICDStackPolicyD95F802D:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ImFrontendCICDStack81ACF762
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              AWS: "*"
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ImFrontendCICDStack81ACF762
                      - Arn
                  - /*
          - Action:
              - s3:DeleteObject*
              - s3:GetBucket*
              - s3:List*
              - s3:PutBucketPolicy
            Effect: Allow
            Principal:
              AWS:
                Fn::GetAtt:
                  - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
                  - Arn
            Resource:
              - Fn::GetAtt:
                  - ImFrontendCICDStack81ACF762
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - ImFrontendCICDStack81ACF762
                        - Arn
                    - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendCICDStack/Policy/Resource
  ImFrontendCICDStackAutoDeleteObjectsCustomResource68FC962F:
    Type: Custom::S3AutoDeleteObjects
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F
          - Arn
      BucketName:
        Ref: ImFrontendCICDStack81ACF762
    DependsOn:
      - ImFrontendCICDStackPolicyD95F802D
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/ImFrontendCICDStack/AutoDeleteObjectsCustomResource/Default
  CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Role
  CustomS3AutoDeleteObjectsCustomResourceProviderHandler9D90184F:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: cdk-hnb659fds-assets-315735600242-eu-central-1
        S3Key: faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6.zip
      Timeout: 900
      MemorySize: 128
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
          - Arn
      Runtime: nodejs22.x
      Description:
        Fn::Join:
          - ""
          - - "Lambda function for auto-deleting objects in "
            - Ref: ImFrontendCICDStack81ACF762
            - " S3 bucket."
    DependsOn:
      - CustomS3AutoDeleteObjectsCustomResourceProviderRole3B1BD092
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/Custom::S3AutoDeleteObjectsCustomResourceProvider/Handler
      aws:asset:path: asset.faa95a81ae7d7373f3e1f242268f904eb748d8d0fdd306e8a6fe515a1905a7d6
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WPQWvCQBCFf4tzlHWr5iDkFo1IC22DHqXIZjPKms2u7MwmleB/Lxg9tD09Zr4383hzOU8SOR2pjia6qifWlLLfsdK1UB0dKJH9Muoaed+DiuxztMj4WZ5RM0HKIaKA0npdF7G0RmdaIxGkMAYB6HS4Xth4BynsksN79pFt1jkIuNzNW1TV82D4FLDxrbKFt0ZfIYUKiYO/goAWAxnvsIL0qCyhgA5LMozrEHzIvY4NOn4EP9Crq/D7F7p9idXRDY3EIEPWvofyPv6zDfwmVpHYN1skH4PGPYzhbnou/vAi+NZUGJaKUGREyDtWJ+NON/GmWvUyW8ipnC1GZzJmEqJj06DcDvoDQlIT0ZQBAAA=
    Metadata:
      aws:cdk:path: ImFrontendCICDStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]