# Root-Logger Level und Appender
rootLogger.level=INFO
rootLogger.appenderRefs=console
rootLogger.appenderRef.console.ref=CONSOLE
# Console Appender
appender.console.type=Console
appender.console.name=CONSOLE
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%d{HH:mm:ss} [%t] %-5level %logger{36} - %msg%n
# Logger für Ihr CDK-Projekt (Package)
logger.cdk.name=com.sakai.cloud.infra.pipeline
logger.cdk.level=DEBUG
logger.cdk.additivity=false
logger.cdk.appenderRef.console.ref=CONSOLE