version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "###########################"
      - echo "Installing AWS CDK"
      - echo "###########################"
      - npm install -g aws-cdk
      - cdk --version
  pre_build:
    commands:
      - echo "build project and running tests..."
      - mvn clean test
  build:
    commands:
      - echo "deploying to DEV..."
      - cd sakai-aws-infrastructure
      - export STAGE_NAME=dev
      - export STACK_NAME=SakaiInfraStackId
      - export ARTIFACT_BUCKET=sakai-lambda-artifacts
      - export OBJECT_KEY=asset-service-1.0-SNAPSHOT.jar
      - cdk deploy ${STACK_NAME} --context stage=${STAGE_NAME} --context artifactBucketName=${ARTIFACT_BUCKET} --context artifactObjectKey=${OBJECT_KEY} --require-approval never
artifacts:
  files:
    - '**/*'