version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing AWS CDK"
      - npm install -g aws-cdk
      - cdk --version
  pre_build:
    commands:
      - echo "build project and running tests..."
      - mvn clean test
  build:
    commands:
      - echo "deploying CloudFormation Stack to DEV..."
      - cd sakai-aws-infrastructure
      - cdk deploy ${STACK_NAME} --context stage=${STAGE_NAME} --context artifactBucketName=${ARTIFACT_BUCKET} --context artifactObjectKey=${OBJECT_KEY} --require-approval never
artifacts:
  files:
    - '**/*'