version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "###########################"
      - echo "Installing AWS CDK"
      - echo "###########################"
      - npm install -g aws-cdk
      - cdk --version
  pre_build:
    commands:
      - echo "build project and running tests..."
      - mvn clean test
  build:
    commands:
      - echo "deploying to DEV..."
      - cdk deploy ${STACK_NAME} --context=dev --require-approval never
      -
artifacts:
  files:
    - '**/*'